Update gopkg.in/yaml.v3 version to address CVE-2022-28948
warrensbox/terraform-switcher pull request #263
Opened 2022-07-20 13:23 UTC by mamccorm

Version 3.0.0 of gopkg.in/yaml.v3 has the following high CVE:
- https://nvd.nist.gov/vuln/detail/CVE-2022-28948
- https://avd.aquasec.com/nvd/cve-2022-28948

This has been addresses in release 3.0.1. This PR is to bump the version containing the required fix.

Disclosure - I have not been able to test this change locally. I've some more work I need to so on my local golang setup.

2022-07-20 13:57 UTC, yermulnik approved these changes
LGTM (since this is a patch version bump testing might be not necessary 🤔)

2022-07-26 07:03 UTC, Jukie requested changes
Please run `go mod tidy` to update go.sum

2022-07-26 07:04 UTC, Jukie commented
@warrensbox any more thoughts on getting dependabot rolling?

2022-07-31 13:16 UTC, warrensbox approved these changes

2024-04-08 13:03 UTC, MatrixCrawler commented
The package is already up to date on master.

2024-04-08 13:03 UTC, closed without merging