feat: Improve logging on reading TOML and TF version constraint
warrensbox/terraform-switcher pull request #363
Opened 2024-04-05 17:04 UTC by yermulnik

Attempt to hastily fix Fatal level calls to logger by appending `os.Exit(1)` to each `logger.Fatal()` (`logger.Fatalf()`) call, as it appeared that it doesn't exit as we'd expect it to.

Refs:
- #334 (comment)
- gookit/slog#143

2024-04-05 17:10 UTC, yermulnik commented
2reviewers: I just added `os.Exit(1)` to every single `logger.Fatal()` call. Including tests. Which (the latter) may probably break some testing logic — please review them as I'm not familiar with Go at the necessary level 🤷🏻 Thank you.

2024-04-05 17:23 UTC, MatrixCrawler requested changes
I don't think we need os.Exit(1) in tests (nor fatal logs)
My expectation is that the tests fails and all the remaining tests are still executed (which they are not if we call os.Exit(1))

2024-04-05 17:34 UTC, yermulnik commented
> I don't think we need os.Exit(1) in tests (nor fatal logs)
> My expectation is that the tests fails and all the remaining tests are still executed (which they are not if we call os.Exit(1))

Reverted test files: 6190226

2024-04-05 17:38 UTC, MatrixCrawler approved these changes
LGTM.
Thanks for your effort

2024-04-05 17:45 UTC, yermulnik commented
👍🏻 
@warrensbox @MatthewJohn @crablab @jukie Please let me know in case explicit exit is needed for tests and I'll add with a separate PR. Thanks.

2024-04-05 17:45 UTC, merged

2024-04-07 13:42 UTC, yermulnik commented
So the exit function has to be explicitly declared at logger init (https://github.com/gookit/slog/issues/143). I'll work on this change in near days. Caveat ℹ️: this would make `logger.Fatal()` calls in test to fail with exit code 1 as well.

2024-04-07 16:57 UTC, MatrixCrawler commented
I will have a look at the test logs. In tests error level should suffice.
And we'd have to look att all other fatals if we'd REALLY really want to exit at this point

2024-04-07 18:23 UTC, yermulnik commented
> I will have a look at the test loggers. In tests error level should suffice.

Thank you.
I'd also much appreciate if you could look into configuring logger as per https://github.com/gookit/slog/issues/143 — given my knowledge of Golang is of a sysadmin level (as in script simple code bits), for me this task is more of a taking wild guesses on how to do that correctly =)
Along with that the other part of this task is to simply remove all the `os.Exit(1)` statements that directly follow `logger.Fatal()` and `logger.Fatalf()` calls.

> And we'd have to look att all other fatals if we'd REALLY really want to exit at this point

When I was reviewing logging re-factoring PR and when I was adding `os.Exit(1)` to all fatals, I tried my best to re-consider whether Fatal is needed or not. So hopefully all of them (or at least vast majority of them) are correctly used.

The other related task I'd think of is to provide an option for a user to customize logging level so that they can reduce or increase amount of log messages they see in console. With that done, we might re-visit all logging statements and configure them more granular by employing more Warns, Notices, Debugs, and Traces (at the moment we mainly use Fatals, Errors and Infos, with some sprinkling with Panic, Notice and Debug I guess).